    LIST p=16f876
    #include p16f876.INC
    __CONFIG _FOSC_XT & _WDTE_OFF & _PWRTE_OFF & _CP_OFF
    
RES_VECT  CODE    0x0000            ; processor reset vector
    GOTO    START                   ; go to beginning of program

; TODO ADD INTERRUPTS HERE IF USED
INT_VECT CODE 0X004	; WHENEVER A ACTIVE INTERRUP OCCUR IT COMES TO THIS LOCATION    
    GOTO ISR		; JUMP TO INTERRUPT SERVICE ROUTINE 

ISR
    COMF PORTC		    ; PULSE START
    BCF INTCON,INTF	    ; CLEAR THE INTERRUPT FLAG
    BSF STATUS, RP0	    ; BANK 1
    MOVLW B'01000000'	    
    XORWF OPTION_REG,1	    ; TOGGLE THE INTERRUPT EDGE	
    BCF STATUS, RP0
    COMF PORTC		    ; PULSE END
    RETFIE
    
START
    BSF STATUS, RP0	    ; BANK 1
    MOVLW 0X0
    MOVWF TRISC		    ; PORTC OUTPUT
    MOVLW 0XFF
    MOVWF TRISB		    ;PORTB INPUT
    BSF OPTION_REG, INTEDG   ;RISING EDGE AT THE START
    BCF STATUS, RP0	    ;BANK 0
    MOVLW B'10010000'		
    MOVWF INTCON	    ;GIE AND INTE SET
    MOVLW 0X0
    MOVWF PORTC
    
LOOP
    GOTO LOOP                           ; loop forever
    END 
